package com.myself.test.db.entity;

import com.myself.test.db.plugin.AutoId;

import java.math.BigDecimal;
import java.util.Date;

public class HotGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.id
     *
     * @mbggenerated
     */
    @AutoId
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.dept
     *
     * @mbggenerated
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.goods_price
     *
     * @mbggenerated
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.crt_user
     *
     * @mbggenerated
     */
    private Long crtUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.upd_user
     *
     * @mbggenerated
     */
    private Long updUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.upd_time
     *
     * @mbggenerated
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_goods.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.id
     *
     * @return the value of hot_goods.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.id
     *
     * @param id the value for hot_goods.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.dept
     *
     * @return the value of hot_goods.dept
     *
     * @mbggenerated
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.dept
     *
     * @param dept the value for hot_goods.dept
     *
     * @mbggenerated
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.goods_name
     *
     * @return the value of hot_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.goods_name
     *
     * @param goodsName the value for hot_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.goods_price
     *
     * @return the value of hot_goods.goods_price
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.goods_price
     *
     * @param goodsPrice the value for hot_goods.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.remark
     *
     * @return the value of hot_goods.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.remark
     *
     * @param remark the value for hot_goods.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.crt_user
     *
     * @return the value of hot_goods.crt_user
     *
     * @mbggenerated
     */
    public Long getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.crt_user
     *
     * @param crtUser the value for hot_goods.crt_user
     *
     * @mbggenerated
     */
    public void setCrtUser(Long crtUser) {
        this.crtUser = crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.crt_time
     *
     * @return the value of hot_goods.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.crt_time
     *
     * @param crtTime the value for hot_goods.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.upd_user
     *
     * @return the value of hot_goods.upd_user
     *
     * @mbggenerated
     */
    public Long getUpdUser() {
        return updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.upd_user
     *
     * @param updUser the value for hot_goods.upd_user
     *
     * @mbggenerated
     */
    public void setUpdUser(Long updUser) {
        this.updUser = updUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.upd_time
     *
     * @return the value of hot_goods.upd_time
     *
     * @mbggenerated
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.upd_time
     *
     * @param updTime the value for hot_goods.upd_time
     *
     * @mbggenerated
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_goods.status
     *
     * @return the value of hot_goods.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_goods.status
     *
     * @param status the value for hot_goods.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}