server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://10.144.157.240:8635/yunlian_truck_jb?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: yunlian_truck_jb
    password: c3ZzkzknkddwgM1e_
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 5
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.myself.test.db.entity
