package com.myself.test.db.mapper;

import com.myself.test.db.entity.HotGoods;

import java.util.List;

public interface HotGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_goods
     *
     * @mbggenerated
     */
    int insert(HotGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_goods
     *
     * @mbggenerated
     */
    int insertSelective(HotGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_goods
     *
     * @mbggenerated
     */
    HotGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotGoods record);


    int batchInsert(List<HotGoods> list);
}